x-environment: &aws_env
  AWS_ACCESS_KEY_ID: test
  AWS_SECRET_ACCESS_KEY: test
  AWS_DEFAULT_REGION: us-east-1

networks:
  airflow:
    driver: bridge

services:
  localstack:
    image: localstack/localstack
    container_name: localstack
    ports:
      - "4566:4566"
    environment:
      <<: *aws_env # Inherit global AWS env variables
      SERVICES: s3
    # - PERSISTENCE=1 This only works for Pro Image
    networks:
      - airflow
    volumes:
      # Avoid anonymous containers
      - localstack_data:/var/lib/localstack

  azurite:
    image: mcr.microsoft.com/azure-storage/azurite
    container_name: azurite
    command: "azurite --blobHost 0.0.0.0 --queueHost 0.0.0.0 --tableHost 0.0.0.0 -l /storage"
    ports:
      - "10000:10000"
      - "10001:10001"
      - "10002:10002"
    networks:
      - airflow
    volumes:
      # Persisting data and avoid anonymous volumes
      # Internal Azurite metadata
      - azurite_data:/data
      # Separate storage for application files (if needed)
      - azurite_storage:/storage

  setup-s3:
    image: amazon/aws-cli
    container_name: setup-s3
    environment:
      <<: *aws_env # Inherit global AWS env variables
    depends_on:
      - localstack
    entrypoint: ["/bin/sh", "-c"]
    networks:
      - airflow
    command:
      - |
        echo "Waiting for LocalStack to start..."
        sleep 5
        echo "Creating S3 bucket..."
        aws --endpoint-url=http://localstack:4566 s3 mb s3://test-bucket
        echo "S3 bucket created."

volumes:
  localstack_data:
    name: airflow-datawarehouse_localstack_internal
  azurite_data:
    name: airflow-datawarehouse_azurite_internal
  azurite_storage:
    name: airflow-datawarehouse_azurite_storage
