services:
  localstack:
    image: localstack/localstack
    container_name: localstack
    ports:
      - "4566:4566"
    environment:
      - SERVICES=s3
      - DEFAULT_REGION=us-east-1
      - DATA_DIR=/var/lib/localstack  # Keep internal files separate
      - LOCALSTACK_VOLUME_DIR=/var/lib/localstack
    volumes:
      # Persisting data and avoid anonymous volumes
      # Internal LocalStack data
      - localstack_data:/var/lib/localstack
      # Separate storage for application files
      - localstack_storage:/data

  azurite:
    image: mcr.microsoft.com/azure-storage/azurite
    container_name: azurite
    command: "azurite -l /var/lib/azurite"
    user: "${UID}:${GID}"  # Run as your user to prevent permission issues
    environment:
      - AZURITE_WORKSPACE=/var/lib/azurite
    ports:
      - "10000:10000"
    volumes:
      # Persisting data and avoid anonymous volumes
      # Internal Azurite data
      - azurite_data:/var/lib/azurite
      # Separate storage for application files
      - azurite_storage:/data

volumes:
  localstack_data:
    name: airflow-datawarehouse_localstack_internal
  localstack_storage:
    name: airflow-datawarehouse_localstack_storage
  azurite_data:
    name: airflow-datawarehouse_azurite_internal
  azurite_storage:
    name: airflow-datawarehouse_azurite_storage
