name: Block Direct Commits

on:
  push:
    branches:
      - master

jobs:
  prevent-direct-commit:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4  # This ensures the repo is available

      - name: Check for direct commits
        run: |
          AUTHOR=$(git log -1 --pretty=format:'%an')
          if [[ "$AUTHOR" != "GitHub" ]]; then
            echo "❌ Direct commits to master are not allowed. Please use a pull request."
            exit 1
          fi
